obstacle_range: 20
raytrace_range: 25
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.105
inflation_radius: 0.05
transform_tolerance: 1
observation_sources: laser_scan_sensor 
use_sim_time: True
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
controller_frequency: 5.0
planner_patience: 5.0
controller_patience: 2.0
conservative_reset_dist: 3.0
planner_frequency: 5.0
oscillation_timeout: 10.0
oscillation_distance: 0.2