DWAPlannerROS:

  global_frame_id: odom

  holonomic_robot: false
  
  # Reduced maximum velocities for slow movement
  max_vel_x: 0.1  # Reduce for slower forward speed
  min_vel_x: -0.1  # Allow slow backward movement

  max_vel_y: 0.1  # Reduce for slower lateral movement
  min_vel_y: -0.1  # Symmetrical lateral speed

  max_vel_trans: 0.1  # Limit the maximum translational speed
  max_vel_theta: 0.01  # Reduce for slower rotation
  min_vel_theta: -0.01

  # Adjust acceleration limits for gentle changes in speed
  acc_lim_x: 0.05  # Smoother acceleration
  acc_lim_y: 0.05  # Smoother lateral acceleration
  acc_lim_theta: 0.02  # Smoother rotational acceleration

  # Tighten goal tolerance for precise stopping
  xy_goal_tolerance: 0.02  # Tighter tolerance for precise positioning
  yaw_goal_tolerance: 0.1  # Tighter tolerance for precise orientation

  # Controller frequencies can remain the same unless testing suggests otherwise
  controller_frequency: 5.0
  planner_frequency: 5.0

  latch_xy_goal_tolerance: true
  
  trans_stopped_vel: 0.01
  theta_stopped_vel: 0

# Forward Simulation Parameters
  sim_time: 4
  vx_samples: 6
  vy_samples: 6
  vth_samples: 20

# Trajectory Scoring Parameters
  path_distance_bias: 64
  goal_distance_bias: 10
  occdist_scale: 0.08
  forward_point_distance: 0.1
  stop_time_buffer: 0.2
  scaling_speed: 0.25
  max_scaling_factor: 0.2

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
  
NavfnROS:
  allow_unknown: true